variables:
  versionbase: 0.1.1
  increment: $[counter(variables['versionbase'], 1)]
  version: $(versionbase).$(increment)

trigger:
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "##vso[build.updatebuildnumber]$(version)"
  displayName: 'Set Build Number'

- checkout: self
  displayName: 'Checkout with submodules'
  submodules: true

- task: UseDotNet@2
  displayName: 'Prepare dotnet core'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: Run release build
  inputs:
    command: 'run'
    projects: 'Build/*.csproj'
    arguments: '-- release build'
    workingDirectory: 'Build'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Publish Binaries Artifact
  inputs:
    pathtoPublish: Output/Release/Binaries
    artifactName: Binaries
    publishLocation: container